//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP245_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spoilage
    {
        public int SpoilageId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public int ReasonType { get; set; }
        public string Description { get; set; }
        public System.DateTime SpoilageDate { get; set; }
        public decimal Value { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
